// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJgAlVnM2qhJFcXDlBU38RXwP5VTN-A2A',
    appId: '1:781086832217:web:724514dd0afa87f7f62348',
    messagingSenderId: '781086832217',
    projectId: 'timbre-qr-delfino',
    authDomain: 'timbre-qr-delfino.firebaseapp.com',
    storageBucket: 'timbre-qr-delfino.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGOjF4wpBYYdxKClM5viT3eR8UU_DmWLE',
    appId: '1:781086832217:android:b8540b6a04da6d25f62348',
    messagingSenderId: '781086832217',
    projectId: 'timbre-qr-delfino',
    storageBucket: 'timbre-qr-delfino.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRdUUFspC5gX-YGmQ-81tNjHfc_xwQZA8',
    appId: '1:781086832217:ios:15a9e04b48cb8865f62348',
    messagingSenderId: '781086832217',
    projectId: 'timbre-qr-delfino',
    storageBucket: 'timbre-qr-delfino.firebasestorage.app',
    iosBundleId: 'com.example.timbreAppQr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRdUUFspC5gX-YGmQ-81tNjHfc_xwQZA8',
    appId: '1:781086832217:ios:15a9e04b48cb8865f62348',
    messagingSenderId: '781086832217',
    projectId: 'timbre-qr-delfino',
    storageBucket: 'timbre-qr-delfino.firebasestorage.app',
    iosBundleId: 'com.example.timbreAppQr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJgAlVnM2qhJFcXDlBU38RXwP5VTN-A2A',
    appId: '1:781086832217:web:671310fab7b4b019f62348',
    messagingSenderId: '781086832217',
    projectId: 'timbre-qr-delfino',
    authDomain: 'timbre-qr-delfino.firebaseapp.com',
    storageBucket: 'timbre-qr-delfino.firebasestorage.app',
  );
}
